### ISSUE TITLE
LAB 17

### ISSUE THREAD

**Issue by UsingCoding** [Koneist/BasicOfProgramming#1]
### 17.1

- [ ] Стоит вынести эту проверку на EOLN в процеуру
https://github.com/Koneist/BasicOfProgramming/blob/3badf1ae48fb19bfa1be07ce019d5bdda021b102/17/17dot1.pas#L28

### 17.2

- [ ] Для этих дел существует константа - MAXINT
https://github.com/Koneist/BasicOfProgramming/blob/3badf1ae48fb19bfa1be07ce019d5bdda021b102/17/17dot2.pas#L46

**Comment by Koneist** [comment]
исправил
